#docker-compose up
version: "3.9"
services:
  deploy:
    container_name: demoapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localDemoDB:5432/local_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      demoapp-network:
        aliases:
          - demoapp
networks:
  demoapp-network:
    name: 'demoapp_network'